CREATE TABLE EMPLOYEES(
    ID INT AUTO-INCREMENT,
   NAME VARCHAR(255),
   AGE  INT,
  SALARY INT,
  PICTURE VARCHAR(255),
  constraint uq1 unique (NAME),
  id bigint generated by default as identity default on null
);